
plugins {
    id 'com.android.application' version '8.7.3' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.24' apply false
}

ext {
    androidxAnnotationVersion = '1.5.0'
    robolectricVersion = '4.9'
    guavaVersion = '31.1-android'
    extTruthVersion = '1.5.0'
    coreVersion = '1.5.0'
    extJUnitVersion = '1.1.5'
    runnerVersion = '1.5.2'
    espressoVersion = '3.5.1'
}
