
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.android.testing.espresso.BasicSample'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.android.testing.espresso.BasicSample'
        minSdk 18
        targetSdk 33
        versionCode 1
        versionName '1.0'

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildFeatures {
        viewBinding true
    }

    lint {
        abortOnError false
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }

        managedDevices {
            devices {
                nexusOneApi30(
                        com.android.build.api.dsl.ManagedVirtualDevice
                ) {
                    device = 'Nexus One'
                    apiLevel = 30
                    systemImageSource = 'aosp-atd'
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    // App dependencies
    implementation "androidx.annotation:annotation:$androidxAnnotationVersion"
    implementation "com.google.guava:guava:$guavaVersion"

    // Instrumentation testing
    androidTestImplementation 'androidx.recyclerview:recyclerview:1.2.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.5.1'
    androidTestImplementation "androidx.test:core:$coreVersion"
    androidTestImplementation "androidx.test:core-ktx:$coreVersion"
    androidTestImplementation "androidx.test.ext:junit:$extJUnitVersion"
    androidTestImplementation "androidx.test.ext:junit-ktx:$extJUnitVersion"
    androidTestImplementation "androidx.test:runner:$runnerVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espressoVersion"

    // Unit testing
    testImplementation "androidx.test:core:$coreVersion"
    testImplementation "androidx.test.ext:junit:$extJUnitVersion"
    testImplementation 'junit:junit:4.13.2'
    testImplementation "org.robolectric:robolectric:$robolectricVersion"
    testImplementation "androidx.test.espresso:espresso-core:$espressoVersion"
    testImplementation "androidx.test.espresso:espresso-intents:$espressoVersion"
    testImplementation "androidx.test.ext:truth:$extTruthVersion"
}